/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.ChatUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatUserRecord extends TableRecordImpl<ChatUserRecord> implements Record5<byte[], String, byte[], String, Integer> {

    private static final long serialVersionUID = -31850384;

    /**
     * Setter for <code>kchat.chat_user.chat_id</code>.
     */
    public void setChatId(byte... value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.chat_user.chat_id</code>.
     */
    public byte[] getChatId() {
        return (byte[]) get(0);
    }

    /**
     * Setter for <code>kchat.chat_user.chat_id_text</code>.
     */
    public void setChatIdText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.chat_user.chat_id_text</code>.
     */
    public String getChatIdText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kchat.chat_user.user_id</code>.
     */
    public void setUserId(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>kchat.chat_user.user_id</code>.
     */
    public byte[] getUserId() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>kchat.chat_user.user_id_text</code>.
     */
    public void setUserIdText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kchat.chat_user.user_id_text</code>.
     */
    public String getUserIdText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kchat.chat_user.contextual_privilege</code>.
     */
    public void setContextualPrivilege(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kchat.chat_user.contextual_privilege</code>.
     */
    public Integer getContextualPrivilege() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<byte[], String, byte[], String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<byte[], String, byte[], String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field1() {
        return ChatUser.CHAT_USER.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ChatUser.CHAT_USER.CHAT_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return ChatUser.CHAT_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ChatUser.CHAT_USER.USER_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ChatUser.CHAT_USER.CONTEXTUAL_PRIVILEGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component1() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getChatIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getContextualPrivilege();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getChatIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getContextualPrivilege();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value1(byte... value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value2(String value) {
        setChatIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value3(byte... value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value4(String value) {
        setUserIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value5(Integer value) {
        setContextualPrivilege(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord values(byte[] value1, String value2, byte[] value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatUserRecord
     */
    public ChatUserRecord() {
        super(ChatUser.CHAT_USER);
    }

    /**
     * Create a detached, initialised ChatUserRecord
     */
    public ChatUserRecord(byte[] chatId, String chatIdText, byte[] userId, String userIdText, Integer contextualPrivilege) {
        super(ChatUser.CHAT_USER);

        set(0, chatId);
        set(1, chatIdText);
        set(2, userId);
        set(3, userIdText);
        set(4, contextualPrivilege);
    }
}
