/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.ChatUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatUserRecord extends TableRecordImpl<ChatUserRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1686886814;

    /**
     * Setter for <code>kchat.chat_user.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.chat_user.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kchat.chat_user.participants_id</code>.
     */
    public void setParticipantsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.chat_user.participants_id</code>.
     */
    public Long getParticipantsId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ChatUser.CHAT_USER.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ChatUser.CHAT_USER.PARTICIPANTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getParticipantsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getParticipantsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value1(Long value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord value2(Long value) {
        setParticipantsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUserRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatUserRecord
     */
    public ChatUserRecord() {
        super(ChatUser.CHAT_USER);
    }

    /**
     * Create a detached, initialised ChatUserRecord
     */
    public ChatUserRecord(Long chatId, Long participantsId) {
        super(ChatUser.CHAT_USER);

        set(0, chatId);
        set(1, participantsId);
    }
}
