/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.Invite;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InviteRecord extends UpdatableRecordImpl<InviteRecord> implements Record11<String, Timestamp, byte[], String, byte[], String, String, Timestamp, byte[], String, Timestamp> {

    private static final long serialVersionUID = 1586976060;

    /**
     * Setter for <code>kchat.invite.token</code>.
     */
    public void setToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.invite.token</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>kchat.invite.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.invite.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>kchat.invite.space_id</code>.
     */
    public void setSpaceId(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>kchat.invite.space_id</code>.
     */
    public byte[] getSpaceId() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>kchat.invite.space_id_text</code>.
     */
    public void setSpaceIdText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kchat.invite.space_id_text</code>.
     */
    public String getSpaceIdText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kchat.invite.creator_id</code>.
     */
    public void setCreatorId(byte... value) {
        set(4, value);
    }

    /**
     * Getter for <code>kchat.invite.creator_id</code>.
     */
    public byte[] getCreatorId() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>kchat.invite.creator_id_text</code>.
     */
    public void setCreatorIdText(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kchat.invite.creator_id_text</code>.
     */
    public String getCreatorIdText() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kchat.invite.memo</code>.
     */
    public void setMemo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kchat.invite.memo</code>.
     */
    public String getMemo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kchat.invite.expires</code>.
     */
    public void setExpires(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>kchat.invite.expires</code>.
     */
    public Timestamp getExpires() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>kchat.invite.recipient_id</code>.
     */
    public void setRecipientId(byte... value) {
        set(8, value);
    }

    /**
     * Getter for <code>kchat.invite.recipient_id</code>.
     */
    public byte[] getRecipientId() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>kchat.invite.recipient_id_text</code>.
     */
    public void setRecipientIdText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kchat.invite.recipient_id_text</code>.
     */
    public String getRecipientIdText() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kchat.invite.date_redeemed</code>.
     */
    public void setDateRedeemed(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>kchat.invite.date_redeemed</code>.
     */
    public Timestamp getDateRedeemed() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Timestamp, byte[], String, byte[], String, String, Timestamp, byte[], String, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Timestamp, byte[], String, byte[], String, String, Timestamp, byte[], String, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Invite.INVITE.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Invite.INVITE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return Invite.INVITE.SPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Invite.INVITE.SPACE_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field5() {
        return Invite.INVITE.CREATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Invite.INVITE.CREATOR_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Invite.INVITE.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Invite.INVITE.EXPIRES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field9() {
        return Invite.INVITE.RECIPIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Invite.INVITE.RECIPIENT_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Invite.INVITE.DATE_REDEEMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSpaceIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component5() {
        return getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCreatorIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getExpires();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component9() {
        return getRecipientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRecipientIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getDateRedeemed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSpaceIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value5() {
        return getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreatorIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getExpires();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value9() {
        return getRecipientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRecipientIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getDateRedeemed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value1(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value2(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value3(byte... value) {
        setSpaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value4(String value) {
        setSpaceIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value5(byte... value) {
        setCreatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value6(String value) {
        setCreatorIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value7(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value8(Timestamp value) {
        setExpires(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value9(byte... value) {
        setRecipientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value10(String value) {
        setRecipientIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord value11(Timestamp value) {
        setDateRedeemed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InviteRecord values(String value1, Timestamp value2, byte[] value3, String value4, byte[] value5, String value6, String value7, Timestamp value8, byte[] value9, String value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InviteRecord
     */
    public InviteRecord() {
        super(Invite.INVITE);
    }

    /**
     * Create a detached, initialised InviteRecord
     */
    public InviteRecord(String token, Timestamp dateCreated, byte[] spaceId, String spaceIdText, byte[] creatorId, String creatorIdText, String memo, Timestamp expires, byte[] recipientId, String recipientIdText, Timestamp dateRedeemed) {
        super(Invite.INVITE);

        set(0, token);
        set(1, dateCreated);
        set(2, spaceId);
        set(3, spaceIdText);
        set(4, creatorId);
        set(5, creatorIdText);
        set(6, memo);
        set(7, expires);
        set(8, recipientId);
        set(9, recipientIdText);
        set(10, dateRedeemed);
    }
}
