/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.Message;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record7<Long, Timestamp, Timestamp, String, Long, Long, Long> {

    private static final long serialVersionUID = -1893466321;

    /**
     * Setter for <code>kchat.message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kchat.message.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.message.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>kchat.message.last_edited</code>.
     */
    public void setLastEdited(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>kchat.message.last_edited</code>.
     */
    public Timestamp getLastEdited() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>kchat.message.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kchat.message.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kchat.message.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>kchat.message.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>kchat.message.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>kchat.message.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>kchat.message.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>kchat.message.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Timestamp, Timestamp, String, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Timestamp, Timestamp, String, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Message.MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Message.MESSAGE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Message.MESSAGE.LAST_EDITED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Message.MESSAGE.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Message.MESSAGE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Message.MESSAGE.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Message.MESSAGE.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getLastEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value2(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value3(Timestamp value) {
        setLastEdited(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value4(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value5(Long value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value6(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value7(Long value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Long id, Timestamp dateCreated, Timestamp lastEdited, String text, Long timestamp, Long authorId, Long chatId) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, dateCreated);
        set(2, lastEdited);
        set(3, text);
        set(4, timestamp);
        set(5, authorId);
        set(6, chatId);
    }
}
