/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.Space;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceRecord extends UpdatableRecordImpl<SpaceRecord> implements Record4<byte[], String, String, Timestamp> {

    private static final long serialVersionUID = 244660063;

    /**
     * Setter for <code>kchat.space.id</code>.
     */
    public void setId(byte... value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.space.id</code>.
     */
    public byte[] getId() {
        return (byte[]) get(0);
    }

    /**
     * Setter for <code>kchat.space.id_text</code>.
     */
    public void setIdText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.space.id_text</code>.
     */
    public String getIdText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kchat.space.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kchat.space.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kchat.space.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>kchat.space.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<byte[]> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<byte[], String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<byte[], String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field1() {
        return Space.SPACE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Space.SPACE.ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Space.SPACE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Space.SPACE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceRecord value1(byte... value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceRecord value2(String value) {
        setIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceRecord value4(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceRecord values(byte[] value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpaceRecord
     */
    public SpaceRecord() {
        super(Space.SPACE);
    }

    /**
     * Create a detached, initialised SpaceRecord
     */
    public SpaceRecord(byte[] id, String idText, String name, Timestamp dateCreated) {
        super(Space.SPACE);

        set(0, id);
        set(1, idText);
        set(2, name);
        set(3, dateCreated);
    }
}
