/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq.tables.records;


import com.natevaughan.kchat.domain.jooq.tables.SpaceUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceUserRecord extends UpdatableRecordImpl<SpaceUserRecord> implements Record6<byte[], String, byte[], String, String, Integer> {

    private static final long serialVersionUID = -839266554;

    /**
     * Setter for <code>kchat.space_user.space_id</code>.
     */
    public void setSpaceId(byte... value) {
        set(0, value);
    }

    /**
     * Getter for <code>kchat.space_user.space_id</code>.
     */
    public byte[] getSpaceId() {
        return (byte[]) get(0);
    }

    /**
     * Setter for <code>kchat.space_user.space_id_text</code>.
     */
    public void setSpaceIdText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kchat.space_user.space_id_text</code>.
     */
    public String getSpaceIdText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kchat.space_user.user_id</code>.
     */
    public void setUserId(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>kchat.space_user.user_id</code>.
     */
    public byte[] getUserId() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>kchat.space_user.user_id_text</code>.
     */
    public void setUserIdText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kchat.space_user.user_id_text</code>.
     */
    public String getUserIdText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kchat.space_user.user_alias</code>.
     */
    public void setUserAlias(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kchat.space_user.user_alias</code>.
     */
    public String getUserAlias() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kchat.space_user.contextual_privilege</code>.
     */
    public void setContextualPrivilege(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>kchat.space_user.contextual_privilege</code>.
     */
    public Integer getContextualPrivilege() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<byte[], byte[]> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<byte[], String, byte[], String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<byte[], String, byte[], String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field1() {
        return SpaceUser.SPACE_USER.SPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SpaceUser.SPACE_USER.SPACE_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return SpaceUser.SPACE_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SpaceUser.SPACE_USER.USER_ID_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SpaceUser.SPACE_USER.USER_ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SpaceUser.SPACE_USER.CONTEXTUAL_PRIVILEGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component1() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSpaceIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getContextualPrivilege();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpaceIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserIdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getContextualPrivilege();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value1(byte... value) {
        setSpaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value2(String value) {
        setSpaceIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value3(byte... value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value4(String value) {
        setUserIdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value5(String value) {
        setUserAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord value6(Integer value) {
        setContextualPrivilege(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpaceUserRecord values(byte[] value1, String value2, byte[] value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpaceUserRecord
     */
    public SpaceUserRecord() {
        super(SpaceUser.SPACE_USER);
    }

    /**
     * Create a detached, initialised SpaceUserRecord
     */
    public SpaceUserRecord(byte[] spaceId, String spaceIdText, byte[] userId, String userIdText, String userAlias, Integer contextualPrivilege) {
        super(SpaceUser.SPACE_USER);

        set(0, spaceId);
        set(1, spaceIdText);
        set(2, userId);
        set(3, userIdText);
        set(4, userAlias);
        set(5, contextualPrivilege);
    }
}
