/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq;


import com.natevaughan.kchat.domain.jooq.tables.Chat;
import com.natevaughan.kchat.domain.jooq.tables.ChatUser;
import com.natevaughan.kchat.domain.jooq.tables.Message;
import com.natevaughan.kchat.domain.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>kchat</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHAT_FKKM9ZE3MECFXQ1HXK = Indexes0.CHAT_FKKM9ZE3MECFXQ1HXK;
    public static final Index CHAT_PRIMARY = Indexes0.CHAT_PRIMARY;
    public static final Index CHAT_USER_FKTIA7RMNDE3JP9CHS = Indexes0.CHAT_USER_FKTIA7RMNDE3JP9CHS;
    public static final Index CHAT_USER_FKWNOLJBCORVGUUN0P = Indexes0.CHAT_USER_FKWNOLJBCORVGUUN0P;
    public static final Index MESSAGE_FKJBUGTZ1C9YJFJDOZ = Indexes0.MESSAGE_FKJBUGTZ1C9YJFJDOZ;
    public static final Index MESSAGE_FKP7PNYAW7PXPLN82B = Indexes0.MESSAGE_FKP7PNYAW7PXPLN82B;
    public static final Index MESSAGE_PRIMARY = Indexes0.MESSAGE_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CHAT_FKKM9ZE3MECFXQ1HXK = Internal.createIndex("FKkM9zE3mecFxq1hxK", Chat.CHAT, new OrderField[] { Chat.CHAT.CREATOR_ID }, false);
        public static Index CHAT_PRIMARY = Internal.createIndex("PRIMARY", Chat.CHAT, new OrderField[] { Chat.CHAT.ID }, true);
        public static Index CHAT_USER_FKTIA7RMNDE3JP9CHS = Internal.createIndex("FKtia7rMnDE3JP9cHs", ChatUser.CHAT_USER, new OrderField[] { ChatUser.CHAT_USER.PARTICIPANTS_ID }, false);
        public static Index CHAT_USER_FKWNOLJBCORVGUUN0P = Internal.createIndex("FKWnoljBcORVgUuN0p", ChatUser.CHAT_USER, new OrderField[] { ChatUser.CHAT_USER.CHAT_ID }, false);
        public static Index MESSAGE_FKJBUGTZ1C9YJFJDOZ = Internal.createIndex("FKJbUgtZ1c9YjFJDOZ", Message.MESSAGE, new OrderField[] { Message.MESSAGE.AUTHOR_ID }, false);
        public static Index MESSAGE_FKP7PNYAW7PXPLN82B = Internal.createIndex("FKp7PNYAW7PxplN82b", Message.MESSAGE, new OrderField[] { Message.MESSAGE.CHAT_ID }, false);
        public static Index MESSAGE_PRIMARY = Internal.createIndex("PRIMARY", Message.MESSAGE, new OrderField[] { Message.MESSAGE.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
