/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq;


import com.natevaughan.kchat.domain.jooq.tables.Chat;
import com.natevaughan.kchat.domain.jooq.tables.ChatUser;
import com.natevaughan.kchat.domain.jooq.tables.Invite;
import com.natevaughan.kchat.domain.jooq.tables.Message;
import com.natevaughan.kchat.domain.jooq.tables.Space;
import com.natevaughan.kchat.domain.jooq.tables.SpaceUser;
import com.natevaughan.kchat.domain.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kchat extends SchemaImpl {

    private static final long serialVersionUID = 595163693;

    /**
     * The reference instance of <code>kchat</code>
     */
    public static final Kchat KCHAT = new Kchat();

    /**
     * The table <code>kchat.chat</code>.
     */
    public final Chat CHAT = com.natevaughan.kchat.domain.jooq.tables.Chat.CHAT;

    /**
     * The table <code>kchat.chat_user</code>.
     */
    public final ChatUser CHAT_USER = com.natevaughan.kchat.domain.jooq.tables.ChatUser.CHAT_USER;

    /**
     * The table <code>kchat.invite</code>.
     */
    public final Invite INVITE = com.natevaughan.kchat.domain.jooq.tables.Invite.INVITE;

    /**
     * The table <code>kchat.message</code>.
     */
    public final Message MESSAGE = com.natevaughan.kchat.domain.jooq.tables.Message.MESSAGE;

    /**
     * The table <code>kchat.space</code>.
     */
    public final Space SPACE = com.natevaughan.kchat.domain.jooq.tables.Space.SPACE;

    /**
     * The table <code>kchat.space_user</code>.
     */
    public final SpaceUser SPACE_USER = com.natevaughan.kchat.domain.jooq.tables.SpaceUser.SPACE_USER;

    /**
     * The table <code>kchat.user</code>.
     */
    public final User USER = com.natevaughan.kchat.domain.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Kchat() {
        super("kchat", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Chat.CHAT,
            ChatUser.CHAT_USER,
            Invite.INVITE,
            Message.MESSAGE,
            Space.SPACE,
            SpaceUser.SPACE_USER,
            User.USER);
    }
}
