/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq;


import com.natevaughan.kchat.domain.jooq.tables.Chat;
import com.natevaughan.kchat.domain.jooq.tables.KchatUser;
import com.natevaughan.kchat.domain.jooq.tables.Message;
import com.natevaughan.kchat.domain.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in kchat
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kchat.chat</code>.
     */
    public static final Chat CHAT = com.natevaughan.kchat.domain.jooq.tables.Chat.CHAT;

    /**
     * The table <code>kchat.kchat_user</code>.
     */
    public static final KchatUser KCHAT_USER = com.natevaughan.kchat.domain.jooq.tables.KchatUser.KCHAT_USER;

    /**
     * The table <code>kchat.message</code>.
     */
    public static final Message MESSAGE = com.natevaughan.kchat.domain.jooq.tables.Message.MESSAGE;

    /**
     * The table <code>kchat.user</code>.
     */
    public static final User USER = com.natevaughan.kchat.domain.jooq.tables.User.USER;
}
