/*
 * This file is generated by jOOQ.
 */
package com.natevaughan.kchat.domain.jooq;


import com.natevaughan.kchat.domain.jooq.tables.Chat;
import com.natevaughan.kchat.domain.jooq.tables.ChatUser;
import com.natevaughan.kchat.domain.jooq.tables.Invite;
import com.natevaughan.kchat.domain.jooq.tables.Message;
import com.natevaughan.kchat.domain.jooq.tables.Space;
import com.natevaughan.kchat.domain.jooq.tables.SpaceUser;
import com.natevaughan.kchat.domain.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in kchat
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kchat.chat</code>.
     */
    public static final Chat CHAT = com.natevaughan.kchat.domain.jooq.tables.Chat.CHAT;

    /**
     * The table <code>kchat.chat_user</code>.
     */
    public static final ChatUser CHAT_USER = com.natevaughan.kchat.domain.jooq.tables.ChatUser.CHAT_USER;

    /**
     * The table <code>kchat.invite</code>.
     */
    public static final Invite INVITE = com.natevaughan.kchat.domain.jooq.tables.Invite.INVITE;

    /**
     * The table <code>kchat.message</code>.
     */
    public static final Message MESSAGE = com.natevaughan.kchat.domain.jooq.tables.Message.MESSAGE;

    /**
     * The table <code>kchat.space</code>.
     */
    public static final Space SPACE = com.natevaughan.kchat.domain.jooq.tables.Space.SPACE;

    /**
     * The table <code>kchat.space_user</code>.
     */
    public static final SpaceUser SPACE_USER = com.natevaughan.kchat.domain.jooq.tables.SpaceUser.SPACE_USER;

    /**
     * The table <code>kchat.user</code>.
     */
    public static final User USER = com.natevaughan.kchat.domain.jooq.tables.User.USER;
}
